import { ModeToggle } from "@/components/mode-toggle";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provieder";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar/>

          {children}

        </ThemeProvider>
      </body>
    </html>
  );
}
